#docker run -d -p 80:80 --name my-apache-php-app -v "$PWD":/var/www/html php:7.2-apache

version: "3.1"

networks:
  default:
  gibbon_net:
    ipam:
      config:
        - subnet: "172.16.238.0/24"

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: gibbon_dev
      MYSQL_USER: gibbon
      MYSQL_PASSWORD: gibbon
    networks:
      gibbon_net:
        ipv4_address: 172.16.238.10
      #ports:
      #- 3306:3306

  apache:
    build: ./
    #image: php:7.4-apache
    restart: always
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
    ports:
      - 8081:80
    volumes:
    - ./:/var/www/html:rw
    networks:
      gibbon_net:
        ipv4_address: 172.16.238.20
      default:
